# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MatchingBox
                                 A QGIS plugin
 This plugins contains a set of algorithms for matching geospatial vector datasets.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-05-31
        copyright            : (C) 2019 by Emerson Xavier
        email                : emerson.xavier@eb.mil.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Emerson Xavier'
__date__ = '2019-05-31'
__copyright__ = '(C) 2019 by Emerson Xavier'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

sys.path.append(os.path.abspath(os.path.dirname(__file__)))

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from matching_box.src.matching_box_provider import MatchingBoxProvider

#cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

#if cmd_folder not in sys.path:
    #sys.path.insert(0, cmd_folder)


class MatchingBox(object):
    """ Plugin main class for Matching Box"""

    def __init__(self):
        self.provider = MatchingBoxProvider()

    def initGui(self):
        QgsApplication.processingRegistry().addProvider(self.provider)

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
